-- 530 Problem Diagnostic Database - Part 1 (Engine + Transmission, IDs 1-100)
INSERT IGNORE INTO kb_problems (`system`, problem, symptoms, causes, solution) VALUES
('Engine','Engine Won''t Start','Cranks but no start, no spark, no fuel','Bad ignition coil, bad spark plug, faulty ECU, bad crankshaft position sensor, no fuel pressure','Check spark, fuel pressure, crankshaft sensor, ECU fault codes; replace faulty parts'),
('Engine','Engine Misfire','Rough idle, hesitation, loss of power, check engine light','Bad spark plug, bad ignition coil, vacuum leak, injector problem, low compression','Replace plugs/coils, check vacuum, test injectors, compression test'),
('Engine','Engine Overheating','Temperature gauge high, steam from hood, coolant loss','Low coolant, bad thermostat, bad water pump, radiator clogged, head gasket failure','Check coolant level, thermostat, water pump, radiator flush, head gasket test'),
('Engine','Engine Stalls','Engine dies while driving, loses power','Bad fuel pump, clogged fuel filter, bad crank sensor, bad MAF, idle control issue','Test fuel pressure, fuel filter, sensors, idle control valve'),
('Engine','Rough Idle','Engine shakes, vibration at idle, RPM fluctuating','Dirty throttle body, vacuum leak, bad spark plugs, bad MAF, engine mounts','Clean throttle body, check vacuum, replace plugs, test MAF, check mounts'),
('Engine','Excessive Smoke - White','White smoke from exhaust, coolant smell','Head gasket failure, cracked block, coolant leaking into cylinder','Compression test, leak-down test, head gasket replacement'),
('Engine','Excessive Smoke - Black','Black smoke from exhaust, soot, fuel smell','Bad fuel injectors, clogged air filter, bad MAF, high fuel pressure','Clean injectors, replace air filter, test MAF, check fuel pressure'),
('Engine','Excessive Smoke - Blue','Blue smoke from exhaust, burning oil smell','Worn piston rings, valve stem seals, turbo oil leak','Compression test, valve seal replacement, piston ring replacement'),
('Engine','Engine Knocking Noise','Knocking sound from engine, worse under load','Low oil pressure, bad bearings, carbon deposit, wrong octane fuel','Check oil level, fuel octane, engine bearing inspection'),
('Engine','Engine Ticking Noise','Ticking sound, worse when cold','Bad lifters, low oil, valve clearance, oil pump issue','Check oil level, lifter replacement, valve adjustment'),
('Engine','Oil Pressure Warning Light','Oil light on, engine noise, low oil pressure','Low oil, bad oil pump, clogged oil filter, bad sensor','Check oil level, oil filter, oil pressure test, sensor check'),
('Engine','Oil Leak','Oil spots under car, burning oil smell, low oil','Bad gaskets, oil pan leak, valve cover leak, rear main seal','Identify leak source, replace gaskets/seals'),
('Engine','Coolant Leak','Coolant under car, overheating, sweet smell','Bad radiator, hose leak, water pump leak, heater core','Pressure test, replace radiator/hoses/water pump'),
('Engine','Timing Belt Slipping','Engine won''t start, misfire, loss of power','Worn timing belt, bad tensioner, misaligned timing','Replace timing belt, tensioner, check timing'),
('Engine','Engine Vibration','Vibration at idle or acceleration','Bad engine mounts, misfire, imbalance','Replace engine mounts, check misfire, balance'),
('Engine','Hesitation on Acceleration','Engine hesitates, loses power, jerks','Bad MAF, clogged fuel filter, bad throttle position sensor, spark plugs','Clean MAF, replace fuel filter, check TPS, plugs'),
('Engine','Loss of Power','Car feels sluggish, won''t accelerate properly','Clogged air filter, bad catalytic converter, fuel pressure, turbo issue','Check air filter, cat, fuel pressure, turbo'),
('Engine','Engine Surging','Engine RPM surges up and down, idle hunting','Vacuum leak, bad IAC, bad TPS, dirty MAF','Check vacuum, clean IAC/MAF, replace TPS'),
('Engine','Low Compression','Loss of power, rough idle, misfire','Worn rings, bad valves, head gasket, timing','Compression test, cylinder leak-down, engine repair'),
('Engine','Engine Backfiring','Pop sounds from exhaust or intake','Timing issue, vacuum leak, fuel mixture, bad plugs','Check timing, vacuum, fuel mixture, plugs'),
('Engine','Pre-ignition / Knocking','Metal pinging, worse under load','Low octane fuel, carbon buildup, bad knock sensor, overheating','Use higher octane, clean carbon, check knock sensor'),
('Engine','Cylinder Compression Loss','Rough running, misfire, blue smoke','Worn rings, valve seat issues, head gasket','Compression test, repair engine'),
('Engine','Valve Train Noise','Clicking/tapping noise, louder at cold start','Worn lifters, low oil pressure, valve clearance','Check oil, lifter replacement, valve adjustment'),
('Engine','Hydraulic Lifter Noise','Ticking noise, worse when cold','Worn lifters, low oil pressure, contaminated oil','Oil change, lifter flush, lifter replacement'),
('Engine','Oil Sludge Build-Up','Poor performance, overheating, oil light flicker','Rare oil changes, bad oil, short trips','Engine flush, frequent oil changes, use quality oil'),
('Engine','Crankshaft Seal Leak','Oil leak at front/rear of engine','Worn seal, high crankcase pressure','Replace seal, check PCV valve'),
('Engine','Camshaft Wear','Ticking noise, loss of power, misfire','Low oil, bad oil pump, contaminated oil','Replace camshaft/lifters, fix oiling'),
('Engine','Piston Ring Failure','Blue smoke, oil consumption, low compression','Worn rings, scored cylinders, overheating','Engine rebuild, replace rings'),
('Engine','Head Gasket Failure','Overheating, white smoke, coolant in oil','Overheating, bad gasket, block warp','Replace head gasket, check block'),
('Engine','Spark Plug Fouling','Misfire, rough idle, poor fuel economy','Worn plugs, bad fuel mixture, oil burning','Replace plugs, fix underlying cause'),
('Engine','Fuel Injector Clogged','Misfire, rough idle, poor fuel economy','Bad fuel, carbon deposit, injector wear','Clean injectors, replace if needed'),
('Engine','Throttle Body Dirty','Rough idle, stalling, poor throttle response','Carbon deposit, bad throttle sensor','Clean throttle body, recalibrate'),
('Engine','MAF Sensor Dirty','Poor fuel economy, hesitation, rough idle','Dust, oil contamination','Clean MAF, replace if needed'),
('Engine','IAC Valve Stuck','Stalling at idle, rough idle','Carbon deposit, bad IAC motor','Clean IAC, replace if needed'),
('Engine','Knock Sensor Failed','Loss of power, pinging, check engine light','Bad sensor, wiring issue','Replace knock sensor, check wiring'),
('Engine','Crankshaft Position Sensor Failed','Engine stalls, won''t start, misfire','Bad sensor, wiring, reluctor ring','Replace sensor, check wiring'),
('Engine','Camshaft Position Sensor Failed','Hard starting, misfire, engine stalls','Bad sensor, timing issue, wiring','Replace sensor, check timing'),
('Engine','Engine ECU Malfunction','Check engine light, no start, poor performance','Bad ECU, wiring, software issue','Reprogram/replace ECU'),
('Engine','Variable Valve Timing (VVT) Issue','Loss of power, rough idle, engine light','Bad solenoid, low oil pressure, chain stretch','Replace VVT solenoid, check oil'),
('Engine','Turbocharger Boost Leak','Loss of power, hissing sound, check engine light','Bad intercooler pipe, loose clamps, bad seals','Inspect boost pipes, replace clamps/seals'),
('Engine','Turbocharger Failure','Loss of power, blue smoke, whining noise','Bad bearings, oil starvation, debris','Replace turbo, fix oil supply'),
('Engine','Wastegate Stuck','Overboost, loss of power, check engine light','Stuck wastegate, bad actuator, boost control','Replace/free wastegate, check actuator'),
('Engine','Intercooler Leak','Loss of power, hissing, higher intake temp','Cracks, bad seals, rock damage','Replace intercooler, check pipes'),
('Engine','PCV Valve Blocked','Oil leaks, rough idle, oil consumption','Clogged PCV, bad hoses','Replace PCV valve, clean hoses'),
('Engine','Vacuum Leak','Rough idle, stalling, lean condition','Cracked hoses, bad gaskets, intake leak','Smoke test, replace hoses/gaskets'),
('Engine','Intake Manifold Leak','Rough idle, misfire, lean code','Bad gasket, cracks','Replace gasket, seal manifold'),
('Engine','Air Filter Clogged','Loss of power, poor fuel economy, black smoke','Dust, dirt','Replace air filter'),
('Engine','Exhaust Manifold Leak','Ticking noise, loss of power, exhaust smell','Bad gasket, cracked manifold','Replace gasket/manifold'),
('Engine','Catalytic Converter Clogged','Loss of power, poor fuel economy, engine light','Carbon buildup, failed cat, bad O2','Replace cat, fix engine first'),
('Engine','O2 Sensor Failed','Poor fuel economy, check engine light, rough running','Bad sensor, wiring, contamination','Replace O2 sensor, check wiring'),
('Transmission','Transmission Won''t Engage Drive','Car won''t move in gear, revs high','Low fluid, bad clutch, solenoid issue, torque converter','Check fluid, clutch, solenoids, torque converter'),
('Transmission','Slipping Gears','Engine revs but car slow, gear slips','Worn clutch, low fluid, bad bands, torque converter','Check fluid level, clutch replacement'),
('Transmission','Rough Shifting','Hard shift, jerk during shift','Low fluid, bad solenoid, worn clutch, TCM issue','Check fluid, solenoid, TCM diagnostics'),
('Transmission','Delayed Engagement','Delay when shifting into gear','Low fluid, bad filter, internal leak, TCM','Check fluid, filter, transmission service'),
('Transmission','Transmission Overheating','Burning smell, slipping, warning light','Low fluid, bad cooler, towing load','Check fluid, cooler, transmission service'),
('Transmission','Fluid Leak','Red fluid under car, slipping, low fluid','Bad pan gasket, seals, cooler lines','Find leak, replace gaskets/seals'),
('Transmission','Grinding When Shifting (Manual)','Grinding sound, hard to engage','Worn synchronizers, clutch not disengaging, low fluid','Replace synchronizers, adjust clutch'),
('Transmission','Hard to Shift (Manual)','Stiff shifting, grinding','Worn clutch, linkage, low fluid','Adjust clutch, check linkage/fluid'),
('Transmission','Transmission Noise','Whining, clunking, humming noise','Low fluid, bad bearings, worn gears','Check fluid, transmission rebuild'),
('Transmission','Check Engine Light Transmission Code','Engine light with trans codes','Sensor, solenoid, TCM issue','Scan codes, repair per code'),
('Transmission','Torque Converter Shudder','Vibration/shudder at low speed','Bad torque converter, low fluid','Replace torque converter, flush fluid'),
('Transmission','Torque Converter Failure','Stalling, poor acceleration, no drive','Worn converter, clutch failure','Replace torque converter'),
('Transmission','Transmission Fluid Dirty','Slipping, harsh shifts, dark fluid','Old fluid, internal wear, overheating','Flush and replace fluid'),
('Transmission','Clutch Pedal Hard','Stiff pedal, hard to press','Bad clutch cable, hydraulic issue','Adjust/replace cable, check hydraulics'),
('Transmission','Clutch Pedal Soft/Spongy','Soft pedal, engages near floor','Low fluid, air in line, bad master/slave','Bleed clutch, replace master/slave'),
('Transmission','Clutch Slipping','Engine revs, car won''t accelerate','Worn clutch, oil on clutch, cable adjust','Replace clutch, fix leaks'),
('Transmission','Clutch Burning Smell','Burning smell when driving','Riding clutch, worn friction, stuck release','Replace clutch, correct driving'),
('Transmission','Clutch Won''t Disengage','Hard to shift, car creeps in neutral','Bad master/slave, air in line, worn disc','Bleed system, replace clutch parts'),
('Transmission','Reverse Gear Not Working','No reverse, grinds in reverse','Bad gear, synchronizer, shift fork, low fluid','Transmission service, repair gearbox'),
('Transmission','First Gear Grinding','Grinds into first gear','Worn synchronizer, clutch not fully disengaging','Replace synchronizer, adjust clutch'),
('Transmission','Third Gear Slipping','Slipping out of third','Worn gears, shift fork, synchronizer','Rebuild transmission'),
('Transmission','Fifth Gear Not Engaging','Hard to engage fifth','Shift fork, synchronizer wear','Replace fork/synchronizer'),
('Transmission','Overdrive Not Working','No overdrive, high RPM at speed','Bad solenoid, TCM, wiring','Check solenoid, TCM diagnostics'),
('Transmission','Transmission Won''t Downshift','Won''t downshift on hills','TCM, solenoid, wiring, throttle cable','Check TCM, solenoids, throttle cable'),
('Transmission','Park Lock Stuck','Can''t shift out of park','Bad brake light switch, shift interlock, stuck solenoid','Check brake light switch, interlock'),
('Transmission','Transmission Judder','Vibration when accelerating','Worn mounts, bad U-joint, torque converter','Check mounts, U-joint, converter'),
('Transmission','Transmission Grinding (Auto)','Grinding in auto mode','Low fluid, internal wear','Check fluid, transmission service'),
('Transmission','CVT Slipping','Revs up, no acceleration, limp mode','Worn belt, low fluid, failing pulley','CVT fluid change, belt replacement'),
('Transmission','CVT Overheating','Warning light, limp mode, burning smell','Low fluid, blocked cooler, aggressive driving','Change fluid, check cooler'),
('Transmission','CVT Belt Failure','Loss of drive, loud noise, shudder','Worn belt, contaminated fluid','Replace CVT belt/pulleys'),
('Transmission','DSG Jerky Shifting','Jerky, harsh shift','Mechatronic issue, low fluid, clutch wear','Mechatronic service, fluid change'),
('Transmission','DSG Slipping','Revs but slow, hesitation','Worn clutch pack, mechatronic fault','Replace clutch pack, mechatronic repair'),
('Transmission','DSG Mechatronic Failure','Gears stuck, warning light, limp mode','Mechatronic unit failure','Replace mechatronic unit'),
('Transmission','Transmission Fluid Overfilled','Foaming, slipping, harsh shifts','Overfill during service','Drain to correct level'),
('Transmission','Transmission Filter Clogged','Slipping, delayed shift, noise','Old filter, debris','Replace filter, flush fluid'),
('Transmission','Shift Linkage Loose','Sloppy shifting, hard to find gears','Worn bushings, loose linkage','Adjust/replace linkage'),
('Transmission','Transmission Mount Worn','Vibration, clunking on shift','Worn mount','Replace mount'),
('Transmission','TCM Failure','Transmission won''t shift, warning light','Bad TCM, wiring, water damage','Replace TCM, check wiring'),
('Transmission','Transmission Solenoid Failure','Harsh shift, stuck gear, warning light','Bad solenoid, wiring','Replace solenoid, check wiring'),
('Transmission','Transmission Valve Body Issue','Harsh shifting, delayed, slipping','Worn valve body, debris','Valve body rebuild/replace'),
('Transmission','Transmission Pan Gasket Leak','Fluid leak from pan','Bad gasket, overtorque','Replace gasket, proper torque'),
('Transmission','Torque Converter Seal Leak','Fluid leak front of trans','Worn seal, converter play','Replace seal/converter'),
('Transmission','Transmission Cooler Leak','Fluid leak at cooler','Bad cooler, lines','Replace cooler/lines'),
('Transmission','U-Joint / CV Joint Failure','Clicking, clunking, vibration','Worn joint, no grease','Replace joint, grease'),
('Transmission','Driveshaft Vibration','Vibration at speed','Bent shaft, bad U-joint, balance','Replace/balance shaft'),
('Transmission','Differential Noise','Whining, clunking from rear','Low fluid, worn gears, bad bearings','Check fluid, differential service'),
('Transmission','Differential Leak','Fluid leak from diff','Bad seal, worn pinion','Replace seals, service diff'),
('Transmission','Axle Seal Leak','Oil leak at axle','Worn seal','Replace seal'),
('Transmission','Axle Shaft Worn','Clicking on turns, vibration','Worn CV joint, boot damage','Replace axle shaft'),
('Transmission','4WD/AWD Issues','No drive to rear, warning light','Bad clutch, actuator, transfer case','Check transfer case, actuators');
-- 530 Problem Diagnostic Database - Part 2 (Brake + Suspension, IDs 101-200)
INSERT IGNORE INTO kb_problems (`system`, problem, symptoms, causes, solution) VALUES
('Brake','Brake Pedal Spongy','Soft brake pedal, longer stopping','Air in lines, low fluid, bad master cylinder','Bleed brakes, check fluid, master cylinder'),
('Brake','Brake Pedal Goes to Floor','Pedal sinks to floor','Fluid leak, bad master cylinder, bad seal','Inspect for leaks, replace master cylinder'),
('Brake','Brake Pedal Hard','Stiff pedal, hard to press','Bad brake booster, vacuum leak, clogged lines','Check booster, vacuum, lines'),
('Brake','Brake Squealing','Squealing when braking','Worn pads, glazed rotors, dust','Replace pads, resurface rotors'),
('Brake','Brake Grinding','Grinding noise when braking','Worn pads, metal-on-metal','Replace pads/rotors immediately'),
('Brake','Brake Pulling to One Side','Car pulls when braking','Stuck caliper, bad hose, brake imbalance','Check calipers, hoses, adjust'),
('Brake','Brake Pulsation','Pulsing pedal, vibration','Warped rotors, uneven pad transfer','Resurface/replace rotors'),
('Brake','Parking Brake Not Holding','Car rolls on hill','Worn shoes, cable stretch','Adjust/replace parking brake'),
('Brake','Brake Light Warning On','Brake warning light on','Low fluid, worn pads, sensor','Check fluid, pads, sensor'),
('Brake','ABS Light On','ABS light, no ABS function','Bad wheel sensor, ABS module, wiring','Scan ABS codes, replace sensor/module'),
('Brake','ABS Not Working','No ABS, wheels lock','Bad sensor, module, wiring','Check sensors, ABS module'),
('Brake','ABS Pump Noisy','Buzzing from ABS','Low fluid, air, failing pump','Check fluid, bleed, replace pump'),
('Brake','Brake Fluid Leak','Fluid under car, low level, soft pedal','Bad lines, calipers, master cylinder','Find leak, replace parts, bleed'),
('Brake','Brake Caliper Stuck','Car pulls, drags, heat from wheel','Seized caliper, bad slide pins','Rebuild/replace caliper'),
('Brake','Brake Rotor Warped','Pulsation, vibration when braking','Overheating, uneven torque','Resurface/replace rotors'),
('Brake','Brake Pad Worn Out','Squealing, grinding, low stopping','Normal wear','Replace pads, inspect rotors'),
('Brake','Brake Hose Swollen','Brake drag, uneven braking','Internal hose failure','Replace hose, bleed system'),
('Brake','Master Cylinder Failure','Pedal sinks, brakes weak','Internal leak, bad seals','Replace master cylinder, bleed'),
('Brake','Brake Booster Failure','Hard pedal, engine stall on brake','Vacuum leak, bad booster','Replace booster, check vacuum'),
('Brake','Brake Fluid Contaminated','Spongy pedal, dark fluid','Moisture, dirt','Flush brake fluid'),
('Brake','Brake Vibration','Vibration through pedal','Warped rotors, wheel balance','Resurface rotors, balance wheels'),
('Brake','Rear Brake Dragging','Heat, smell, pull','Stuck caliper, bad cable','Check rear calipers/cables'),
('Brake','Front Brake Overheating','Heat, fade, smell','Stuck caliper, driving style','Check caliper, replace pads'),
('Brake','Brake Fade','Reduced stopping, pedal goes low','Overheated brakes, bad fluid','Cool down, flush fluid'),
('Brake','Emergency Brake Stuck','Car drags, won''t release','Rusted cable, seized caliper','Lube/replace cable'),
('Brake','ABS Sensor Dirty','ABS light, no ABS','Dirt, metal shavings','Clean sensor, check gap'),
('Brake','ABS Sensor Failed','ABS light on, no speed reading','Bad sensor, wiring','Replace sensor'),
('Brake','Brake Light Switch Failed','Brake lights not working','Bad switch','Replace switch'),
('Brake','Brake Lights Not Working','No brake lights','Bad bulb, fuse, switch','Check bulb, fuse, switch'),
('Brake','Brake Pedal Vibrates','Vibrating pedal','Warped rotors, ABS activation','Check rotors, ABS'),
('Brake','Disc Brake Noise','Noise from disc brakes','Pads, rotors, dust shields','Inspect, replace as needed'),
('Brake','Drum Brake Noise','Noise from rear drum','Worn shoes, drum, hardware','Replace shoes, service drums'),
('Brake','Brake Lines Rusted','Weak brake, leak','Rust, corrosion','Replace lines, bleed'),
('Brake','Brake Fluid Dark','Spongy pedal, poor braking','Old fluid, contamination','Flush system'),
('Brake','Parking Brake Cable Stretched','Doesn''t hold, lever high','Cable stretch','Adjust/replace cable'),
('Brake','Wheel Cylinder Leak (Drum)','Fluid leak, soft pedal','Worn seal','Replace wheel cylinder, bleed'),
('Brake','Proportioning Valve Issue','Uneven braking','Bad valve','Replace valve, bleed'),
('Brake','Brake Warning Light Stays On','Light stays on','Low fluid, pads, sensor','Check and fix'),
('Brake','Rear Brake Light Not Working','No rear light','Bulb, wiring, switch','Replace bulb, check wiring'),
('Brake','Brake Disc Worn','Grooves, vibration, noise','Normal wear, metal pads','Replace discs'),
('Brake','Brake Drum Worn','Poor braking, noise','Wear, scored drum','Replace drum, shoes'),
('Brake','Brake Booster Vacuum Leak','Hard pedal, hissing','Bad hose, check valve','Replace hose/valve'),
('Brake','ABS Module Failed','ABS light, no ABS, brake issue','Module failure, wiring','Replace module, bleed'),
('Brake','Brake Fluid Level Low','Warning light, soft pedal','Leak, worn pads','Top up, find leak'),
('Brake','Front Caliper Seal Leak','Fluid on wheel','Worn seal','Rebuild caliper, bleed'),
('Brake','Brake Shoes Worn (Drum)','Noise, poor braking','Normal wear','Replace shoes'),
('Brake','Parking Brake Light On','Light on with brake applied','Switch, adjustment','Check switch, adjust'),
('Brake','Brake Warning Light Flashes','Flashing brake light','Low fluid, sensor','Check fluid/sensor'),
('Brake','Brake Performance Poor','Weak braking','Pads, fluid, booster, lines','Inspect system, replace parts'),
('Brake','Brake Rotor Scoring','Grooves, noise, poor stopping','Worn pads, debris','Replace rotors/pads'),
('Suspension','Shock Absorber Leaking','Oil on shock, bouncy ride','Worn seal','Replace shocks'),
('Suspension','Worn Shock Absorbers','Bouncy ride, poor handling','Normal wear','Replace shocks'),
('Suspension','Broken Coil Spring','Sagging, noise, poor ride','Fatigue, corrosion, pothole','Replace springs'),
('Suspension','Sagging Suspension','Car sits low, bottoming out','Worn springs','Replace springs'),
('Suspension','Clunking Noise Over Bumps','Clunk when hitting bumps','Worn bushings, ball joints, struts','Replace worn parts'),
('Suspension','Squeaking Suspension','Squeak over bumps','Dry bushings, ball joints','Lubricate/replace'),
('Suspension','Worn Strut Mounts','Noise, steering wobble','Worn mount bearing','Replace strut mounts'),
('Suspension','Worn Control Arm Bushings','Clunking, steering play','Worn rubber bushings','Replace bushings'),
('Suspension','Bad Ball Joints','Clunk, steering play, tire wear','Worn joint','Replace ball joints'),
('Suspension','Worn Tie Rod Ends','Loose steering, vibration','Worn ends','Replace tie rods, align'),
('Suspension','Bad Sway Bar Links','Clunking, noise on turns','Worn links','Replace links'),
('Suspension','Broken Sway Bar','Clunking, body roll','Fatigue','Replace sway bar'),
('Suspension','Worn Bushings','Noise, poor handling','Age, wear','Replace bushings'),
('Suspension','Steering Wander','Car drifts, needs correction','Alignment, worn parts','Align, replace worn'),
('Suspension','Steering Wheel Vibration','Vibration in wheel','Wheel balance, tires, brakes','Balance, rotate, check'),
('Suspension','Car Pulls to One Side','Pulls while driving','Alignment, tire pressure, brake drag','Align, check tires/brakes'),
('Suspension','Uneven Tire Wear','Wear on one edge','Alignment, worn parts, pressure','Align, replace parts'),
('Suspension','Cupped Tires','Scalloped wear','Bad shocks, alignment','Replace shocks, align'),
('Suspension','Wheel Wobble','Wobble at speed','Balance, wheel damage','Balance/replace wheel'),
('Suspension','Poor Handling','Car feels unstable','Worn shocks, springs, tires','Replace worn, check tires'),
('Suspension','Rear End Sways','Rear feels loose','Worn bushings, shocks','Replace worn'),
('Suspension','Bottoming Out','Hits bottom over bumps','Worn springs, shocks','Replace springs/shocks'),
('Suspension','Vehicle Leaning in Turns','Body roll in turns','Worn sway bar, shocks','Replace sway bar/shocks'),
('Suspension','Nose Diving','Nose dips on braking','Worn front shocks','Replace front shocks'),
('Suspension','Excessive Bounce','Bounces after bumps','Worn shocks','Replace shocks'),
('Suspension','Steering Hard (Hydraulic)','Hard to turn','Low fluid, bad pump, belt','Check fluid, pump, belt'),
('Suspension','Steering Noisy','Whining when turning','Low fluid, bad pump','Check fluid, pump'),
('Suspension','Power Steering Fluid Leak','Fluid under front','Bad pump, lines, rack','Find leak, replace parts'),
('Suspension','Power Steering Pump Failure','Hard steering, whine','Worn pump','Replace pump'),
('Suspension','Steering Rack Leak','Fluid at rack boots','Worn seals','Replace rack'),
('Suspension','Steering Play','Loose steering wheel','Worn rack, tie rods, ball joints','Replace worn parts'),
('Suspension','Electric Steering Warning','Steering warning light','EPS motor, sensor, wiring','Scan, replace EPS'),
('Suspension','Stiff Steering (EPS)','Hard steering','EPS issue','Scan EPS, repair'),
('Suspension','Steering Wheel Off Center','Wheel not straight','Alignment','Align vehicle'),
('Suspension','Shimmy at Speed','Vibrates at speed','Balance, tires','Balance/rotate tires'),
('Suspension','Clunking in Front','Clunk on bumps/turns','Sway links, ball joints','Inspect, replace'),
('Suspension','Clunking in Rear','Clunk in rear','Shocks, bushings, links','Inspect, replace'),
('Suspension','Creaking Suspension','Creak when entering car','Worn bushings','Lubricate/replace'),
('Suspension','Torsion Bar Issue','Sagging, uneven height','Worn bars, adjuster','Adjust/replace torsion bars'),
('Suspension','Air Suspension Leak','Car sinks, compressor runs','Air leak, bad bags','Find leak, replace bags'),
('Suspension','Air Suspension Compressor Fails','Car stays low','Compressor failure','Replace compressor'),
('Suspension','Ride Height Too Low','Sits low','Air leak, springs, sensors','Check air, springs, sensors'),
('Suspension','Ride Height Too High','Sits high','Sensor, leveling issue','Check sensors, level'),
('Suspension','Adaptive Suspension Fault','Warning light, stiff ride','Sensor, actuator','Scan, replace parts'),
('Suspension','Strut Bearing Noise','Noise when turning','Worn bearing','Replace strut bearing'),
('Suspension','Lower Arm Worn','Clunk, tire wear','Worn bushing/ball joint','Replace lower arm'),
('Suspension','Upper Arm Worn','Noise, alignment issue','Worn bushing','Replace upper arm'),
('Suspension','Knuckle Worn','Noise, play','Worn bearing','Replace knuckle'),
('Suspension','Wheel Bearing Worn','Humming, grinding, loose wheel','Worn bearing','Replace wheel bearing'),
('Suspension','Coil Spring Sag','Car leans, ride low','Fatigue','Replace springs');
-- 530 Problem Diagnostic Database - Part 3 (Electrical + Cooling + AC, IDs 201-350)
INSERT IGNORE INTO kb_problems (`system`, problem, symptoms, causes, solution) VALUES
('Electrical','Battery Dead','No crank, dim lights','Old battery, parasitic drain','Jump start, replace battery, find drain'),
('Electrical','Battery Won''t Hold Charge','Dies quickly','Bad battery, alternator, drain','Test battery/alternator, fix drain'),
('Electrical','Corroded Battery Terminals','No start, poor connection','Corrosion, acid','Clean terminals'),
('Electrical','Alternator Failure','Battery light, dim lights, dies','Worn brushes, bad diode, belt','Replace alternator'),
('Electrical','Alternator Not Charging','Battery dies, light on','Bad alternator, belt, wiring','Test output, replace alternator'),
('Electrical','Starter Motor Failure','Click no crank','Bad solenoid, worn motor','Replace starter'),
('Electrical','Starter Clicking','Click click, no start','Low battery, bad starter','Check battery, replace starter'),
('Electrical','Starter Grinding','Grind on start','Worn ring gear, starter','Replace starter/flywheel'),
('Electrical','Spark Plug Wiring Fault','Misfire, no start','Bad wires, corrosion','Replace wires'),
('Electrical','Ignition Coil Failure','Misfire, rough idle','Bad coil','Replace coil'),
('Electrical','Distributor Failure','No spark, misfire','Bad cap, rotor, sensor','Replace distributor parts'),
('Electrical','Blown Fuse','Electrical device dead','Short, overload','Replace fuse, find cause'),
('Electrical','Headlight Not Working','No headlights','Bulb, fuse, relay, switch','Test bulb, fuse, relay'),
('Electrical','Headlight Dim','Dim lights','Bad bulb, alternator, wiring','Check bulb, voltage'),
('Electrical','Tail Light Not Working','No tail lights','Bulb, fuse, wiring','Check bulb, fuse'),
('Electrical','Brake Light Bulb Out','No brake light','Bad bulb','Replace bulb'),
('Electrical','Turn Signal Not Working','No blinkers','Bulb, flasher, switch','Test bulb, flasher, switch'),
('Electrical','Turn Signal Fast Blink','Fast flashing','Bulb out, wrong bulb','Replace bulb'),
('Electrical','Hazard Lights Not Working','No hazards','Fuse, flasher, switch','Check fuse, flasher'),
('Electrical','Interior Lights Not Working','No interior light','Bulb, fuse, door switch','Check bulb, fuse'),
('Electrical','Dashboard Lights Dim','Dim dash','Dimmer, alternator, wiring','Check dimmer, voltage'),
('Electrical','Check Engine Light On','Light on','Various causes','Scan codes, fix per code'),
('Electrical','Check Engine Light Flashing','Flashing light','Misfire, serious issue','Stop, scan codes immediately'),
('Electrical','ABS Warning Light','ABS light on','Sensor, module','Scan, check sensors'),
('Electrical','Airbag Light On','Airbag light on','Sensor, clock spring, module','Scan airbag codes'),
('Electrical','Battery Warning Light','Battery light on','Alternator, battery, wiring','Test charging system'),
('Electrical','Oil Pressure Light Flickers','Flickers at idle','Low oil, sensor, pump','Check oil, sensor, pump'),
('Electrical','Temperature Gauge Not Working','No temp reading','Sensor, gauge, wiring','Test sensor, gauge'),
('Electrical','Fuel Gauge Not Working','No fuel reading','Sensor, wiring, gauge','Check sensor, wiring'),
('Electrical','Speedometer Not Working','No speed reading','Sensor, wiring, cluster','Check VSS, cluster'),
('Electrical','Odometer Not Working','No mileage','Cluster, sensor','Replace cluster/sensor'),
('Electrical','Windshield Wipers Not Working','No wipers','Motor, fuse, switch','Test motor, fuse, switch'),
('Electrical','Wipers Slow','Slow wipers','Motor, linkage, wiring','Check motor, linkage'),
('Electrical','Wiper Blade Streaking','Streaks, skips','Worn blades','Replace blades'),
('Electrical','Power Window Not Working','No window movement','Motor, switch, regulator','Test motor, switch'),
('Electrical','Window Slow','Slow window','Regulator, motor, binding','Lube/replace regulator'),
('Electrical','Power Lock Not Working','No lock action','Actuator, switch, wiring','Test actuator, switch'),
('Electrical','Remote Key Not Working','No remote lock','Battery, key fob, receiver','Check battery, reprogram'),
('Electrical','Horn Not Working','No horn','Fuse, relay, horn, switch','Test fuse, horn, switch'),
('Electrical','Cigarette Lighter Not Working','No power','Fuse, socket','Replace fuse, socket'),
('Electrical','USB Port Not Charging','No charge','Fuse, port','Replace fuse/port'),
('Electrical','Radio Not Working','No radio','Fuse, wiring, unit','Check fuse, unit'),
('Electrical','Central Locking Not Working','No central lock','Actuators, control unit','Check unit, actuators'),
('Electrical','Immobilizer Issue','Won''t start, key light','Key chip, receiver','Reprogram key, check receiver'),
('Electrical','Key Stuck in Ignition','Can''t remove key','Interlock, tumbler','Adjust/lube, replace'),
('Electrical','Headlight Adjustment','Beam too low/high','Misadjusted','Adjust beam'),
('Electrical','Fog Light Not Working','No fog light','Bulb, fuse, switch','Check bulb, fuse'),
('Electrical','Reverse Light Not Working','No reverse light','Bulb, switch, wiring','Check bulb, switch'),
('Electrical','License Plate Light Not Working','No plate light','Bulb, wiring','Replace bulb'),
('Electrical','Electrical Short','Blown fuses, smoke smell','Wiring damage','Trace and repair wiring'),
('Cooling','Radiator Leak','Coolant leak, overheating','Damage, corrosion','Replace radiator'),
('Cooling','Radiator Clogged','Overheating, poor flow','Debris, scale','Flush/replace radiator'),
('Cooling','Radiator Cap Failing','Overheating, coolant loss','Bad cap','Replace cap'),
('Cooling','Coolant Low','Overheating, light','Leak, consumption','Find leak, top up'),
('Cooling','Coolant Smells Sweet','Leak, sweet smell','Leak in system','Find and fix leak'),
('Cooling','Water Pump Leak','Leak front of engine, overheating','Bad seal, bearing','Replace water pump'),
('Cooling','Water Pump Failure','Overheating, noise','Worn bearing','Replace water pump'),
('Cooling','Thermostat Stuck Open','Low temp, poor heat','Stuck open','Replace thermostat'),
('Cooling','Thermostat Stuck Closed','Overheating, no heat','Stuck closed','Replace thermostat'),
('Cooling','Cooling Fan Not Working','Overheating at idle','Bad motor, fuse, sensor','Test fan, fuse, sensor'),
('Cooling','Fan Motor Failure','No fan','Bad motor','Replace fan motor'),
('Cooling','Fan Relay Failure','No fan','Bad relay','Replace relay'),
('Cooling','Coolant Temperature Sensor Bad','Wrong temp reading','Bad sensor','Replace sensor'),
('Cooling','Coolant Hoses Worn','Leaks, bulges','Age, heat','Replace hoses'),
('Cooling','Heater Not Working','No heat in cabin','Heater core, thermostat, valve','Check core, thermostat'),
('Cooling','Heater Core Clogged','Poor heat','Debris','Flush/replace core'),
('Cooling','Heater Core Leak','Wet carpet, smell','Leak','Replace core'),
('Cooling','Coolant Mixing With Oil','Milky oil, overheating','Head gasket, block','Fix head gasket'),
('Cooling','Coolant Mixing With Transmission Fluid','Pink milkshake','Trans cooler leak','Fix cooler, flush'),
('Cooling','Overheating at High Speed','Overheats on highway','Thermostat, radiator, water pump','Check system'),
('Cooling','Overheating at Idle','Overheats when stopped','Fan, thermostat','Check fan, thermostat'),
('Cooling','Coolant Overflow','Coolant in reservoir overflows','Overheat, bad cap','Check cooling system'),
('Cooling','Coolant Reservoir Cracked','Leak at reservoir','Crack','Replace reservoir'),
('Cooling','Bleed Screw Leak','Leak at bleed screw','Loose, damaged','Replace screw'),
('Cooling','Expansion Tank Leak','Leak at tank','Crack','Replace tank'),
('Cooling','Coolant Smell Inside Cabin','Sweet smell inside','Heater core leak','Replace core'),
('Cooling','Engine Coolant Foaming','Foam in reservoir','Wrong coolant, air','Flush, bleed'),
('Cooling','Coolant Boiling','Bubbling in reservoir','Overheat, cap, head gasket','Fix cooling, test'),
('Cooling','Water Pump Noise','Whine from pump','Worn bearing','Replace water pump'),
('Cooling','Fan Clutch Failure','No fan at temp','Bad clutch','Replace fan clutch'),
('Cooling','Viscous Fan Not Engaging','Overheats','Bad clutch','Replace clutch'),
('Cooling','Electric Fan Runs Always','Fan always on','Sensor, relay, wiring','Check sensor, relay'),
('Cooling','Electric Fan Never Runs','Overheats at idle','Motor, fuse, relay','Test fan circuit'),
('Cooling','Coolant Level Sensor Fault','Low coolant light on','Sensor, wiring','Replace sensor'),
('Cooling','Radiator Fins Damaged','Poor cooling','Debris, rocks','Clean/repair fins'),
('Cooling','Intercooler Not Cooling','High intake temps','Clogged, damaged','Clean/replace intercooler'),
('Cooling','Coolant Contaminated','Discolored coolant','Old fluid, oil mix','Flush, refill'),
('Cooling','Freeze Plug Leak','Coolant leak at block','Corrosion','Replace freeze plug'),
('Cooling','Head Gasket Coolant Pass','Coolant loss, white smoke','Head gasket','Replace gasket'),
('Cooling','Overheating After Repairs','Overheats after work','Air in system, bad parts','Bleed, verify parts'),
('Cooling','Coolant Level Drops Overnight','Coolant low in morning','Leak','Pressure test, find leak'),
('Cooling','Heater Blows Cold','No heat','Thermostat, core, valve','Check thermostat first'),
('Cooling','Heater Blows Warm Not Hot','Warm air only','Blend door, core, valve','Check blend door, core'),
('Cooling','Temperature Gauge High','Gauge high but no overheat','Sensor, wiring, actual','Test sensor, verify temp'),
('Cooling','Coolant Type Mixed','Corrosion, gel','Mixed coolant types','Flush immediately'),
('Cooling','Engine Block Heater Issue','Cold start hard','Bad heater','Replace heater'),
('Cooling','Coolant Odor','Sweet smell','Leak','Find leak'),
('Cooling','Poor Cabin Heat at Idle','Heat drops at idle','Low coolant, air, pump','Check coolant, bleed'),
('Cooling','Radiator Pressure Test Fail','Holds no pressure','Leaks, cap','Fix leaks, replace cap'),
('Cooling','Coolant System Rust','Rusty coolant','Old fluid','Flush system'),
('AC','AC Not Cooling','Warm air','Low refrigerant, compressor, leak','Check refrigerant, compressor, leak test'),
('AC','AC Weak Cooling','Slightly warm','Low refrigerant, dirty condenser','Recharge, clean condenser'),
('AC','AC Blowing Warm Air','No cold air','Compressor, clutch, low gas','Check compressor, clutch, charge'),
('AC','AC Compressor Not Engaging','No compressor clutch','Relay, fuse, sensor, clutch','Test clutch, relay, fuse'),
('AC','AC Compressor Noisy','Noise from compressor','Worn bearing, clutch','Replace compressor'),
('AC','AC Compressor Seized','Belt squeal, no AC','Seized','Replace compressor'),
('AC','AC Refrigerant Leak','Low cooling, hissing','Leak in system','Leak test, fix, recharge'),
('AC','AC Condenser Leak','Leak at front','Rock damage','Replace condenser'),
('AC','AC Evaporator Leak','Low cooling, smell','Leak','Replace evaporator'),
('AC','AC Expansion Valve Fault','Poor cooling, frost','Bad valve','Replace valve'),
('AC','AC Drier/Receiver Fault','Poor cooling','Moisture, clog','Replace drier'),
('AC','AC Orifice Tube Clogged','No cooling','Debris','Replace tube, flush'),
('AC','AC Blower Not Working','No airflow','Motor, resistor, fuse','Test motor, resistor'),
('AC','AC Blower Slow','Weak airflow','Resistor, motor','Replace resistor/motor'),
('AC','AC Blower Noisy','Noise from blower','Debris, worn motor','Clean, replace motor'),
('AC','AC Not Blowing Cold Enough','Low temp','Low charge, filter, condenser','Check charge, condenser'),
('AC','AC Smells Musty','Bad smell from vents','Mold in evaporator','Clean evaporator, cabin filter'),
('AC','AC Smells Burning','Burning smell','Electrical, blower motor','Check motor, wiring'),
('AC','AC Condensate Drain Clogged','Water in cabin','Clogged drain','Clear drain'),
('AC','AC Water Leak Inside','Water on floor','Clogged drain','Clear drain'),
('AC','AC Temperature Fluctuates','Inconsistent temp','Sensor, door, charge','Check sensor, charge'),
('AC','AC Compressor Clutch Slipping','Intermittent cooling','Worn clutch','Replace clutch'),
('AC','AC Compressor Clutch Gap Wrong','No engage','Gap too large','Adjust gap'),
('AC','AC Compressor Cycling Fast','Rapid on/off','Low charge, sensor','Check charge, sensor'),
('AC','AC Not Cooling at Idle','Cools when driving','Condenser airflow, fan','Clean condenser, check fan'),
('AC','AC Poor Cooling at High Speed','Worse on highway','Clogged condenser','Clean/replace condenser'),
('AC','AC Recirculation Door Stuck','Outside air always','Door actuator','Replace actuator'),
('AC','AC Blend Door Stuck','No temp change','Actuator, door','Replace actuator'),
('AC','AC Airflow Direction Fault','Vents stuck','Actuator','Replace actuator'),
('AC','AC Rear Vents No Air','No rear airflow','Blower, duct, setting','Check duct, fan'),
('AC','AC Defroster Not Working','No windshield heat','Blend door, heater','Check door, heater'),
('AC','AC Snow on Lines','Frost on AC lines','Low charge, orifice','Check charge, orifice'),
('AC','AC Gauge Readings Low','Low pressure','Low gas, leak','Recharge, leak test'),
('AC','AC Gauge Readings High','High pressure','Overcharge, blocked condenser','Recover, clean condenser'),
('AC','AC Noisy on Start','Noise at startup','Clutch, belt, compressor','Inspect, replace'),
('AC','AC Belt Squeal','Squeal when AC on','Worn belt','Replace belt'),
('AC','AC Fan Relay Fault','No fan','Bad relay','Replace relay'),
('AC','AC Fuse Blown','No AC power','Short, motor','Replace fuse, trace'),
('AC','AC Wiring Short','Intermittent AC','Wiring damage','Trace, repair'),
('AC','AC Control Panel Dead','No controls','Fuse, unit','Check fuse, unit'),
('AC','AC Light Blinking','Blinking indicator','Fault code','Scan AC codes'),
('AC','Cabin Air Filter Clogged','Weak airflow','Dirty filter','Replace filter'),
('AC','Cabin Air Filter Smelly','Bad odor','Dirty filter','Replace filter'),
('AC','AC Refrigerant Overcharged','High pressure, weak cool','Overcharge','Recover, recharge correct'),
('AC','AC System Moisture','Inefficient cooling','Moisture in system','Evacuate, replace drier'),
('AC','AC Evaporator Freezing','Frost, low airflow','Thermostat, charge','Check thermostat, charge'),
('AC','AC High-Side Pressure Too High','Poor cooling','Blockage, overcharge','Check blockage, charge'),
('AC','AC Low-Side Pressure Too Low','No cooling','Low charge, leak','Find leak, charge'),
('AC','AC Compressor Seal Leak','Oil at compressor','Worn seal','Replace seal/compressor'),
('AC','AC Not Working After Repair','Still no AC','Incorrect charge, leaks','Verify charge, leak test');
-- 530 Problem Diagnostic Database - Part 4 (Fuel + Hybrid + EV + Sensors, IDs 351-530)
INSERT IGNORE INTO kb_problems (`system`, problem, symptoms, causes, solution) VALUES
('Fuel','Fuel Pump Failure','No start, stalls','Worn pump, clogged filter','Replace pump, filter'),
('Fuel','Fuel Pump Noisy','Whine from tank','Worn pump, low fuel','Replace pump'),
('Fuel','Fuel Filter Clogged','Loss of power, stall','Dirt','Replace filter'),
('Fuel','Fuel Injector Leak','Fuel smell, poor economy','Bad seals','Replace injector'),
('Fuel','Fuel Injector Dirty','Misfire, rough idle','Deposits','Clean injectors'),
('Fuel','Fuel Pressure Low','Poor power, no start','Pump, filter, regulator','Test pressure, fix'),
('Fuel','Fuel Pressure High','Rich running, smell','Bad regulator','Replace regulator'),
('Fuel','Fuel Pressure Regulator Fault','Poor running','Bad regulator','Replace regulator'),
('Fuel','Fuel Tank Leak','Fuel smell, leak','Damage, rust','Replace/repair tank'),
('Fuel','Fuel Lines Leaking','Fuel smell, leak','Rust, damage','Replace lines'),
('Fuel','Fuel Odor Inside','Fuel smell in cabin','Leak, lines, canister','Find leak, fix'),
('Fuel','Bad Fuel Quality','Stalling, poor power','Contaminated fuel','Drain, flush, refill'),
('Fuel','Fuel Gauge Inaccurate','Wrong reading','Sender, wiring','Replace sender'),
('Fuel','Fuel Sender Fault','Gauge stuck','Bad sender','Replace sender'),
('Fuel','EVAP Canister Full','Fuel smell, pressure','Clogged canister','Replace canister'),
('Fuel','EVAP Leak','Check engine light, smell','Hose, cap, valve','Smoke test, fix'),
('Fuel','Gas Cap Not Sealing','EVAP code','Bad cap','Replace cap'),
('Fuel','Fuel Pressure Damper Fault','Noise, pressure drop','Bad damper','Replace damper'),
('Fuel','Carburetor Issue (Old)','Poor idle, stalling','Clogged jets','Rebuild carb'),
('Fuel','Carburetor Flooding','Fuel smell, poor start','Float, needle','Rebuild carb'),
('Fuel','Throttle Position Sensor Fault','Hesitation, idle issue','Bad TPS','Replace TPS'),
('Fuel','TPS Miscalibration','Throttle response off','Misadjusted','Calibrate TPS'),
('Fuel','Accelerator Cable Stretched','Pedal slack','Stretched cable','Adjust/replace cable'),
('Fuel','Cruise Control Not Working','No cruise','Switch, actuator, wiring','Test switch, actuator'),
('Fuel','Fuel Smell When Filling','Smell at fill','Canister, vapor lines','Check canister lines'),
('Fuel','Ethanol Fuel Issues','Poor running on E85','Ethanol content','Use correct fuel'),
('Fuel','Diesel Fuel Gelling','Won''t start in cold','Waxing','Add anti-gel'),
('Fuel','Diesel Injector Fault','Misfire, smoke','Bad injector','Replace injector'),
('Fuel','Diesel Glow Plug Fault','Hard start cold','Bad plugs','Replace plugs'),
('Fuel','Diesel Fuel Filter Clogged','Loss of power','Dirt, water','Replace filter, drain water'),
('Fuel','Diesel Water in Fuel','Rough running','Water in tank','Drain, replace filter'),
('Fuel','CNG System Fault','No start on CNG','Regulator, converter','Check CNG system'),
('Fuel','CNG Leak','Gas smell','Line leak','Fix leak, test'),
('Fuel','LPG Conversion Issue','Poor running','Mixer, converter','Tune LPG system'),
('Fuel','Fuel Tank Vent Clogged','Pressure in tank','Clogged vent','Clear vent'),
('Fuel','Fuel Pressure Sensor Fault','Poor running','Bad sensor','Replace sensor'),
('Fuel','Fuel Level Float Stuck','Gauge stuck','Stuck float','Replace sender'),
('Fuel','Fuel Pump Relay Fault','No start, no fuel pump','Bad relay','Replace relay'),
('Fuel','Fuel Pump Fuse Blown','No pump','Short, overload','Replace fuse, trace'),
('Fuel','Fuel Pump Strainer Clogged','Starvation','Debris','Replace strainer'),
('Fuel','Fuel Rail Leak','Fuel smell, leak','Seals, cracks','Replace rail'),
('Fuel','Fuel Injector Wiring Fault','Misfire','Wiring damage','Repair wiring'),
('Fuel','Fuel Pressure Fluctuating','Surge, stall','Regulator, pump','Test pressure, fix'),
('Fuel','Fuel Economy Poor','High consumption','Many causes','Diagnose, fix cause'),
('Fuel','Fuel Octane Requirement','Knocking','Low octane','Use correct octane'),
('Fuel','Fuel Return Line Clogged','High pressure','Clog','Clear line'),
('Fuel','Fuel Heater Fault (Diesel)','Hard start cold','Bad heater','Replace heater'),
('Fuel','Fuel Quality Effect on Injectors','Injector issues','Bad fuel','Clean, use quality fuel'),
('Fuel','Fuel Additive Damage','Poor running','Wrong additives','Flush, use right additives'),
('Fuel','Fuel Metering Issues','Poor performance','Sensor, injector issues','Diagnose fuel system'),
('Hybrid','Hybrid Battery Low','Hybrid battery warning','Battery degradation, cell failure','Battery service, replace cells'),
('Hybrid','Hybrid Battery Overheating','Warning light, reduced power','Cooling fan, blocked vents','Check battery cooling'),
('Hybrid','Hybrid System Malfunction','Warning, reduced power','Inverter, battery, wiring','Scan hybrid codes'),
('Hybrid','Hybrid Battery Not Charging','Low battery','Charger, inverter, wiring','Check charging system'),
('Hybrid','Hybrid Fuel Economy Poor','Low MPG','Battery, engine cycling','Diagnose system'),
('Hybrid','Hybrid Engine Won''t Start','No engine start','12V battery, hybrid battery, system','Check 12V, hybrid system'),
('Hybrid','Hybrid Warning Light','Warning on','Various hybrid faults','Scan codes'),
('Hybrid','Hybrid Battery Cell Failure','Reduced range','Bad cell','Replace cell pack'),
('Hybrid','Hybrid Inverter Fault','Warning, no power','Inverter failure','Replace inverter'),
('Hybrid','Hybrid Motor Fault','Loss of drive','Motor, sensor','Scan, repair motor'),
('Hybrid','Hybrid Regenerative Braking Fault','No regen','Battery, motor, wiring','Check regen system'),
('Hybrid','Hybrid Battery Cooling Fan Fault','Overheating','Fan failure','Replace fan'),
('Hybrid','Hybrid System Loses Power','Limp mode','Battery, cooling','Diagnose, fix'),
('Hybrid','Hybrid Battery Voltage Low','Low voltage warning','Cell imbalance','Balance/charge'),
('Hybrid','Hybrid Battery Check Light','Check light','Various','Scan codes'),
('Hybrid','Hybrid Coolant Pump Fault','Overheating battery','Pump failure','Replace pump'),
('Hybrid','Hybrid Transmission Fault','No drive','E-CVT fault','Scan, repair'),
('Hybrid','Hybrid E-CVT Noise','Whine','Bearing, fluid','Check fluid, service'),
('Hybrid','Hybrid Engine Running Rough','Rough idle','Engine misfire, hybrid issue','Diagnose both'),
('Hybrid','Hybrid Start Stop Issue','No stop/start','Battery, sensor, system','Check 12V, sensors'),
('Hybrid','Hybrid Battery Degradation','Reduced range, warning','Age, cycles','Battery refurbish'),
('Hybrid','Hybrid 12V Battery Fault','No start, warning','12V dead','Replace 12V battery'),
('Hybrid','Hybrid Thermal Management Fault','Battery temp warning','Cooling fault','Check cooling system'),
('Hybrid','Hybrid Drive Motor Overheat','Reduced power','Cooling, load','Check motor cooling'),
('Hybrid','Hybrid Power Cable Fault','Warning','Wiring damage','Inspect cables'),
('Hybrid','Hybrid Service Required','Service light','Scheduled, faults','Service, scan'),
('Hybrid','Hybrid Battery Charge Low','Low charge','Charging fault','Check charging'),
('Hybrid','Hybrid Not Switching to EV','Engine always on','Battery low, system fault','Check battery, system'),
('Hybrid','Hybrid Engine Noise','Unusual engine sound','ICE issue','Diagnose engine'),
('Hybrid','Hybrid Exhaust Smoke','Smoke','Engine issue','Diagnose'),
('Hybrid','Hybrid Brake Feel Odd','Weird pedal feel','Regen transition','Check regen/brakes'),
('Hybrid','Hybrid Air Conditioning Weak','Weak AC','Electric compressor','Check compressor'),
('Hybrid','Hybrid AC Compressor Fault','No AC','Compressor fault','Replace compressor'),
('Hybrid','Hybrid Battery Voltage Imbalance','Warning','Cell imbalance','Balance cells'),
('Hybrid','Hybrid Diagnostics Codes','Various codes','Various','Scan and repair'),
('Hybrid','Hybrid Battery Fan Noise','Noise from battery','Fan bearings','Replace fan'),
('Hybrid','Hybrid Software Update Needed','Performance issue','Outdated software','Update software'),
('Hybrid','Hybrid 12V Charging Issue','12V dies','DC-DC converter','Check converter'),
('Hybrid','Hybrid Inverter Cooling Fault','Warning','Coolant, pump','Check cooling'),
('Hybrid','Hybrid Noise at Low Speed','Whine at low speed','Motor, gear','Diagnose'),
('Hybrid','Hybrid Battery Enclosure Damage','Warning','Physical damage','Inspect, repair'),
('Hybrid','Hybrid High Voltage Disconnect','No power','Safety disconnect','Reset, inspect'),
('Hybrid','Hybrid Traction Battery Warning','Battery warning','Various','Scan codes'),
('Hybrid','Hybrid Fuel Tank Sealed','No refuel','Sealed tank system','Check vent system'),
('Hybrid','Hybrid Engine Idle High','High idle','Engine system','Diagnose engine'),
('Hybrid','Hybrid Battery Range Drop','Less EV range','Battery, temperature','Check battery'),
('Hybrid','Hybrid Charge Port Fault','No charge','Port, wiring','Check port'),
('Hybrid','Hybrid Charging Cable Fault','No charge','Cable damage','Replace cable'),
('Hybrid','Hybrid Charging Slow','Slow charge','Charger, supply','Check charger'),
('Hybrid','Hybrid Charging Not Starting','No charge','Port, cable, timer','Check port, timer'),
('EV','EV Won''t Charge','No charge','Charger, port, battery','Check charger, port'),
('EV','EV Slow Charging','Slow charge','Charger, wiring, temp','Check charger, temp'),
('EV','EV Charging Stops Midway','Stops charging','Thermal, connector','Check connector, temp'),
('EV','EV Range Reduced','Less range','Battery, climate, driving','Check battery health'),
('EV','EV Battery Warning','Warning light','Various','Scan codes'),
('EV','EV Battery Overheating','Warning, reduced power','Cooling fault','Check battery cooling'),
('EV','EV Battery Degradation','Range loss','Age, cycles','Battery health check'),
('EV','EV Motor Fault','Loss of power','Motor, inverter','Scan, repair'),
('EV','EV Inverter Fault','No drive, warning','Inverter failure','Replace inverter'),
('EV','EV Not Starting','No power on','12V battery, contactor','Check 12V, contactor'),
('EV','EV 12V Battery Dead','No systems','12V drained','Replace 12V'),
('EV','EV Thermal Management Fault','Temp warning','Coolant, pump','Check cooling'),
('EV','EV Coolant Pump Fault','Overheating','Pump failure','Replace pump'),
('EV','EV Cabin Heater Fault','No heat','Heater element','Replace heater'),
('EV','EV AC Compressor Fault','No AC','Compressor','Replace compressor'),
('EV','EV Regenerative Braking Fault','No regen','Motor, battery, software','Check regen system'),
('EV','EV Brake Pedal Feel','Odd feel','Regen/blend','Check system'),
('EV','EV Charging Port Fault','No charge','Port damage','Repair port'),
('EV','EV Charging Cable Fault','No charge','Cable damage','Replace cable'),
('EV','EV Software Update Needed','Glitches','Outdated software','Update'),
('EV','EV Infotainment Fault','Screen issues','Software, hardware','Reset/update'),
('EV','EV Connectivity Fault','No app connect','Module, network','Check module'),
('EV','EV Battery Cell Imbalance','Warning, range','Cell issue','Balance cells'),
('EV','EV Battery Contactors Fault','No power','Contactor failure','Replace contactor'),
('EV','EV High Voltage Warning','Warning','Insulation fault','Check insulation'),
('EV','EV Insulation Fault','Warning','Damaged wiring','Test insulation'),
('EV','EV Charging Door Stuck','Can''t open port','Actuator, latch','Manual release'),
('EV','EV Charge Port Light Fault','No light','Wiring, LED','Check wiring'),
('EV','EV Battery Coolant Leak','Leak, warning','Hose, pump','Fix leak'),
('EV','EV Battery Coolant Low','Warning','Leak, service','Top up, find leak'),
('EV','EV Drive Unit Noise','Noise from motor','Bearing, gear','Diagnose'),
('EV','EV Creep Function Fault','No creep','Software, motor','Check software'),
('EV','EV Parking Brake Auto Fault','Auto brake issue','Module, sensor','Scan, repair'),
('EV','EV Hill Hold Fault','Rolls back','System fault','Scan, repair'),
('EV','EV One Pedal Driving Fault','No one pedal','Software','Update/reset'),
('EV','EV Charging Speed Reduced','Slow','Thermal, supply','Check supply'),
('EV','EV AC Charge Fault','No AC charge','Onboard charger','Replace charger'),
('EV','EV DC Fast Charge Fault','No DC charge','Charger, battery','Check battery temp'),
('EV','EV Battery Precondition Fault','Slow charge','BMS, heater','Check BMS'),
('EV','EV BMS Fault','Various warnings','BMS issue','Scan, update'),
('EV','EV Battery Health Low','Reduced range','Degradation','Battery service'),
('EV','EV Whine at Speed','Whine','Motor, gear','Diagnose'),
('EV','EV Shudder on Accel','Shudder','Motor mount, gear','Check mounts'),
('EV','EV Steering Warning','Steering light','EPS fault','Scan EPS'),
('EV','EV Suspension Warning','Suspension light','Air, sensor','Scan, fix'),
('EV','EV Tire Wear Pattern','Uneven wear','Alignment, pressure','Align, adjust'),
('EV','EV Battery Firmware','Range issue','Old firmware','Update firmware'),
('EV','EV Charging Timer Fault','No timed charge','Timer setting','Reset timer'),
('EV','EV Preconditioning Fault','No preheat','Heater, BMS','Check heater'),
('EV','EV Noises from Charger','Noise from charger','Fan, component','Inspect charger'),
('Sensors','O2 Sensor Fault','Poor economy, engine light','Bad sensor','Replace sensor'),
('Sensors','O2 Sensor Slow Response','Fuel trims off','Aging sensor','Replace sensor'),
('Sensors','MAF Sensor Contaminated','Poor running','Dirt, oil','Clean/replace'),
('Sensors','MAP Sensor Fault','Poor running, light','Bad sensor','Replace sensor'),
('Sensors','Throttle Position Sensor Fault','Hesitation, idle','Bad sensor','Replace sensor'),
('Sensors','Crankshaft Sensor Fault','No start, stall','Bad sensor','Replace sensor'),
('Sensors','Camshaft Sensor Fault','Hard start, misfire','Bad sensor','Replace sensor'),
('Sensors','Knock Sensor Fault','Pinging, power loss','Bad sensor','Replace sensor'),
('Sensors','Wheel Speed Sensor Fault','ABS light','Bad sensor','Replace sensor'),
('Sensors','Coolant Temp Sensor Fault','Gauge issue','Bad sensor','Replace sensor'),
('Sensors','Intake Air Temp Sensor Fault','Poor running','Bad sensor','Replace sensor'),
('Sensors','Fuel Temp Sensor Fault','Poor running','Bad sensor','Replace sensor'),
('Sensors','Oil Pressure Sensor Fault','Oil light','Bad sensor','Replace sensor'),
('Sensors','Fuel Pressure Sensor Fault','Poor running','Bad sensor','Replace sensor'),
('Sensors','Ambient Temp Sensor Fault','Gauge wrong','Bad sensor','Replace sensor'),
('Sensors','Rain Sensor Fault','Wipers auto issue','Bad sensor','Replace sensor'),
('Sensors','Light Sensor Fault','Auto lights issue','Bad sensor','Replace sensor'),
('Sensors','Parking Sensor Fault','No beeps','Bad sensor','Replace sensor'),
('Sensors','Backup Camera Fault','No image','Camera, wiring','Check camera'),
('Sensors','Blind Spot Sensor Fault','Warning','Bad sensor','Replace sensor'),
('Sensors','Lane Departure Fault','Warning','Camera, sensor','Replace/calibrate'),
('Sensors','ACC Sensor Fault','No adaptive cruise','Sensor blocked/dirty','Clean, calibrate'),
('Sensors','Tire Pressure Sensor Fault','TPMS light','Bad sensor, battery','Replace sensor'),
('Sensors','TPMS Light On','Light on','Low pressure, sensor','Check pressure, sensor'),
('Sensors','Airbag Sensor Fault','Airbag light','Sensor, wiring','Scan, replace'),
('Sensors','Seat Belt Sensor Fault','Chime always','Sensor, wiring','Replace sensor'),
('Sensors','Brake Light Switch Fault','Brake lights, cruise','Bad switch','Replace switch'),
('Sensors','Clutch Position Sensor Fault','No start','Bad sensor','Replace sensor'),
('Sensors','Throttle Position Sensor Calibration','Off throttle','Calibration','Recalibrate'),
('Sensors','Multi-Sensor Communication Fault','Various warnings','CAN bus, wiring','Check CAN bus, modules');
