<?php
/**
 * Wrench n Parts — Config File Generator
 * 
 * Hosting details bharo → Ready config files download karo
 * 
 * Usage:
 * 1. Browser me kholo: config-generator.php
 * 2. Details fill karo
 * 3. "Download Config Files" button dabao
 * 4. Downloaded files ko hosting pe upload karo
 */

// Generate configs if form submitted
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = trim($_POST['db_pass'] ?? '');
    $dbName = trim($_POST['db_name'] ?? '');
    $siteUrl = rtrim(trim($_POST['site_url'] ?? ''), '/');

    // Validate
    $errors = [];
    if (empty($dbUser)) $errors[] = "DB Username is required";
    if (empty($dbName)) $errors[] = "DB Name is required";
    if (empty($siteUrl)) $errors[] = "Site URL is required";
    if (!preg_match('#^https?://#', $siteUrl)) $errors[] = "Site URL must start with http:// or https://";

    if (empty($errors)) {
        // Generate config.php
        $configPhp = '<?php
date_default_timezone_set(\'Asia/Karachi\');
session_start();

// Database Configuration
define(\'DB_HOST\', \'' . addslashes($dbHost) . '\');
define(\'DB_USER\', \'' . addslashes($dbUser) . '\');
define(\'DB_PASS\', \'' . addslashes($dbPass) . '\');
define(\'DB_NAME\', \'' . addslashes($dbName) . '\');

// Site URL (no trailing slash)
define(\'SITE_URL\', \'' . addslashes($siteUrl) . '\');

// Upload Directory
define(\'UPLOAD_DIR\', __DIR__ . \'/../uploads/\');

// Database Connection
$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
$conn->set_charset("utf8mb4");
$conn->query("SET time_zone = \'+05:00\'");
?>';

        // Generate chatbot config
        $chatbotConfig = '<?php
/**
 * Chatbot API Configuration
 * Auto-generated by Config Generator
 */

// Database Configuration (same as includes/config.php)
define(\'DB_HOST\', \'' . addslashes($dbHost) . '\');
define(\'DB_USER\', \'' . addslashes($dbUser) . '\');
define(\'DB_PASS\', \'' . addslashes($dbPass) . '\');
define(\'DB_NAME\', \'' . addslashes($dbName) . '\');

session_start();

$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
if ($conn->connect_error) {
    http_response_code(500);
    echo json_encode(["error" => "Database connection failed"]);
    exit;
}
$conn->set_charset("utf8mb4");

// CORS Headers
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization");
header("Content-Type: application/json; charset=UTF-8");

if ($_SERVER[\'REQUEST_METHOD\'] === \'OPTIONS\') {
    http_response_code(200);
    exit;
}
?>';

        // Generate .htaccess
        $htaccess = 'RewriteEngine On

# Force HTTPS
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Remove www (optional — uncomment if needed)
# RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]
# RewriteRule ^(.*)$ https://%1/$1 [R=301,L]

# Block sensitive files
<FilesMatch "\.(sql|md|log|env|bak)$">
    Require all denied
</FilesMatch>

# Block PHP execution in uploads
<Directory "uploads">
    <Files "*.php">
        Require all denied
    </Files>
</Directory>

# Remove server signature
ServerSignature Off
Header unset X-Powered-By

# Security headers
Header set X-Content-Type-Options "nosniff"
Header set X-Frame-Options "SAMEORIGIN"
Header set X-XSS-Protection "1; mode=block"

# Enable compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/css
    AddOutputFilterByType DEFLATE application/javascript application/json
</IfModule>

# Cache static files
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/svg+xml "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
</IfModule>';

        // Create ZIP with all config files
        $zipFile = tempnam(sys_get_temp_dir(), 'wnp_config_') . '.zip';
        $zip = new ZipArchive();
        if ($zip->open($zipFile, ZipArchive::CREATE) === true) {
            $zip->addFromString('config.php', $configPhp);
            $zip->addFromString('chatbot-config.php', $chatbotConfig);
            $zip->addFromString('.htaccess', $htaccess);
            
            // Add instruction file
            $instructions = "WRENCH N PARTS — CONFIG FILES\n";
            $instructions .= "================================\n\n";
            $instructions .= "FILES INCLUDED:\n";
            $instructions .= "1. config.php → Copy to: includes/config.php\n";
            $instructions .= "2. chatbot-config.php → Copy to: chatbot/api.php (replace first 20 lines)\n";
            $instructions .= "3. .htaccess → Copy to: public_html/.htaccess\n\n";
            $instructions .= "YOUR SETTINGS:\n";
            $instructions .= "DB Host: $dbHost\n";
            $instructions .= "DB User: $dbUser\n";
            $instructions .= "DB Name: $dbName\n";
            $instructions .= "Site URL: $siteUrl\n\n";
            $instructions .= "STEPS:\n";
            $instructions .= "1. Upload all files to hosting via File Manager\n";
            $instructions .= "2. Import database.sql in phpMyAdmin\n";
            $instructions .= "3. Open your website!\n";
            
            $zip->addFromString('README.txt', $instructions);
            $zip->close();
        }

        // Send file
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="Wrench_n_Parts_Config.zip"');
        header('Content-Length: ' . filesize($zipFile));
        readfile($zipFile);
        unlink($zipFile);
        exit;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wrench n Parts — Config Generator</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <style>
        :root {
            --primary: #dc3545;
            --dark: #1a1a2e;
            --darker: #16213e;
        }
        body {
            background: linear-gradient(135deg, var(--dark), var(--darker));
            color: #e8e8e8;
            min-height: 100vh;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .generator-container {
            max-width: 650px;
            margin: 40px auto;
            padding: 0 20px;
        }
        .gen-header {
            text-align: center;
            padding: 40px 20px;
            background: linear-gradient(135deg, var(--primary), #a71d2a);
            border-radius: 20px 20px 0 0;
        }
        .gen-header h1 { font-size: 2rem; font-weight: 800; margin-bottom: 8px; }
        .gen-header p { opacity: 0.9; font-size: 1rem; }
        .gen-form {
            background: rgba(255,255,255,0.05);
            border: 1px solid rgba(255,255,255,0.1);
            border-radius: 0 0 20px 20px;
            padding: 35px;
            backdrop-filter: blur(10px);
        }
        .form-group { margin-bottom: 20px; }
        .form-group label {
            display: block;
            font-weight: 600;
            margin-bottom: 8px;
            font-size: 0.95rem;
        }
        .form-group label .hint {
            font-weight: 400;
            color: rgba(255,255,255,0.5);
            font-size: 0.85rem;
        }
        .form-control {
            background: rgba(255,255,255,0.08);
            border: 1px solid rgba(255,255,255,0.15);
            color: #fff;
            padding: 12px 16px;
            border-radius: 10px;
            font-size: 1rem;
            width: 100%;
            transition: border-color 0.3s;
        }
        .form-control:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(220, 53, 69, 0.2);
        }
        .form-control::placeholder { color: rgba(255,255,255,0.3); }
        .btn-generate {
            width: 100%;
            padding: 14px;
            background: linear-gradient(135deg, var(--primary), #a71d2a);
            color: #fff;
            border: none;
            border-radius: 12px;
            font-size: 1.1rem;
            font-weight: 700;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
            margin-top: 10px;
        }
        .btn-generate:hover {
            transform: translateY(-2px);
            box-shadow: 0 8px 25px rgba(220, 53, 69, 0.4);
        }
        .info-box {
            background: rgba(220, 53, 69, 0.1);
            border-left: 4px solid var(--primary);
            padding: 15px 20px;
            border-radius: 0 10px 10px 0;
            margin-bottom: 25px;
            font-size: 0.9rem;
        }
        .info-box i { color: var(--primary); margin-right: 8px; }
        .output-info {
            background: rgba(40, 167, 69, 0.1);
            border: 1px solid rgba(40, 167, 69, 0.3);
            border-radius: 12px;
            padding: 20px;
            margin-top: 25px;
            display: none;
        }
        .output-info h4 { color: #28a745; margin-bottom: 12px; }
        .output-info ul { padding-left: 20px; margin: 0; }
        .output-info li { margin-bottom: 6px; font-size: 0.9rem; }
    </style>
</head>
<body>
    <div class="generator-container">
        <div class="gen-header">
            <h1><i class="fas fa-cog"></i> Config Generator</h1>
            <p>Fill hosting details → Download ready config files</p>
        </div>
        <div class="gen-form">
            <div class="info-box">
                <i class="fas fa-info-circle"></i>
                Ye form aapke hosting details lekar <strong>3 ready files</strong> banayega. Unhe hosting pe upload karo — website live!
            </div>

            <form method="POST" id="configForm">
                <div class="form-group">
                    <label>Site URL <span class="hint">(your live domain)</span></label>
                    <input type="url" name="site_url" class="form-control" 
                           placeholder="https://wrenchnparts.com" required
                           value="https://">
                </div>

                <div class="form-group">
                    <label>DB Host <span class="hint">(usually "localhost")</span></label>
                    <input type="text" name="db_host" class="form-control" 
                           placeholder="localhost" value="localhost">
                </div>

                <div class="form-group">
                    <label>DB Username <span class="hint">(from cPanel)</span></label>
                    <input type="text" name="db_user" class="form-control" 
                           placeholder="wnp_user" required>
                </div>

                <div class="form-group">
                    <label>DB Password <span class="hint">(from cPanel)</span></label>
                    <input type="password" name="db_pass" class="form-control" 
                           placeholder="Your database password">
                </div>

                <div class="form-group">
                    <label>DB Name <span class="hint">(from cPanel)</span></label>
                    <input type="text" name="db_name" class="form-control" 
                           placeholder="wrench_parts_db" required>
                </div>

                <button type="submit" class="btn-generate">
                    <i class="fas fa-download"></i> Download Config Files (ZIP)
                </button>
            </form>

            <div class="output-info" id="outputInfo">
                <h4><i class="fas fa-check-circle"></i> Files Generated!</h4>
                <p>ZIP file download ho rahi hai. Isme hain:</p>
                <ul>
                    <li><strong>config.php</strong> → Copy to: <code>includes/config.php</code></li>
                    <li><strong>chatbot-config.php</strong> → Copy to: <code>chatbot/api.php</code> (replace first 20 lines)</li>
                    <li><strong>.htaccess</strong> → Copy to: <code>public_html/.htaccess</code></li>
                    <li><strong>README.txt</strong> → Instructions</li>
                </ul>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('configForm').addEventListener('submit', function() {
            setTimeout(function() {
                document.getElementById('outputInfo').style.display = 'block';
            }, 500);
        });
    </script>
</body>
</html>
